default: &default
  adapter: mysql2
  encoding: utf8
  host: MYSQL5019.site4now.net
  database: db_9bc590_gateway
  username: 9bc590_gateway
  password: Password@abc123
  write_timeout: 10
  read_timeout: 10

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
